name:                   Cargo deny

on:
  pull_request:
  schedule:
    - cron:             '0 0 * * *'
  push:
    branches:
      - master
    tags:
      - v*
    paths-ignore:
      - 'README.md'
jobs:
  cargo-deny:
    runs-on:            ubuntu-latest
    steps:
      - name:           Cancel Previous Runs
        uses:           styfle/cancel-workflow-action@3155a141048f8f89c06b4cdae32e7853e97536bc # 0.13.0
        with:
          access_token: ${{ github.token }}
      - name:           Checkout sources & submodules
        uses:           actions/checkout@v6
        with:
          fetch-depth:  5
          submodules:   recursive
      - name:           Cargo deny
        uses:           EmbarkStudios/cargo-deny-action@v2
        with:
          command:      "check --hide-inclusion-graph"
