name:                   Cargo deny

on:
  pull_request:
  schedule:
    - cron:             '0 0 * * *'
  push:
    branches:
      - master
    tags:
      - v*
    paths-ignore:
      - 'README.md'
jobs:
  cargo-deny:
    runs-on:            ubuntu-latest
    steps:
      - name:           Cancel Previous Runs
        uses:           styfle/cancel-workflow-action@85880fa0301c86cca9da44039ee3bb12d3bedbfa # 0.12.1
        with:
          access_token: ${{ github.token }}
      - name:           Checkout sources & submodules
        uses:           actions/checkout@v5
        with:
          fetch-depth:  5
          submodules:   recursive
      - name:           Cargo deny
        uses:           EmbarkStudios/cargo-deny-action@v2
        with:
          command:      "check --hide-inclusion-graph"
