name:                   Check style

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*
    paths-ignore:
      - 'README.md'
jobs:
## Check stage
  check-fmt:
    name:                          Check RustFmt
    runs-on:                       ubuntu-latest
    env:
      RUST_BACKTRACE:   full
    steps:
      - name:           Cancel Previous Runs
        uses:           styfle/cancel-workflow-action@01ce38bf961b4e243a6342cbade0dbc8ba3f0432 # 0.12.0
        with:
          access_token: ${{ github.token }}
      - name:           Checkout sources & submodules
        uses:           actions/checkout@v4
        with:
          fetch-depth:  5
          submodules:   recursive
      - name:           Add rustfmt
        run:            rustup component add rustfmt
      - name:           rust-fmt check
        uses:           actions-rs/cargo@v1
        with:
          command:      fmt
          args:         --all -- --check
